version: '3'

services:
  www:
    build: docker/php
    container_name: relogio_de_ponto
    ports:
      - "8741:8124"
    volumes:
      - ./docker/php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    restart: always
    networks:
      - relogio_de_ponto

networks:
  relogio_de_ponto:

